# Generated by Django 4.1.5 on 2023-01-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.CharField(default='', max_length=50)),
                ('users', models.CharField(default='', max_length=50)),
                ('speed', models.CharField(default='', max_length=50)),
                ('encryption', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
