# Generated by Django 4.1.5 on 2023-01-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pricepanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricepanel',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
