# Generated by Django 4.1.5 on 2023-01-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pricepanel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricepanel',
            name='link',
            field=models.CharField(default='', max_length=250),
        ),
    ]
